In [1]:
from scipy import linalg
import numpy as np

In [2]:
# 3x1 + 2x2 = 12
# 2x1 - 1x2 = 1

a = np.array([
    [3, 2],
    [2, -1]
])

b = np.array([12, 1]).reshape(2, 1)


In [3]:
ans = np.linalg.solve(a, b)

In [4]:
print(*ans)

[2.] [3.]


In [5]:
#Meal Plan
# Assume that a balanced diet should include the following:

# 170 units of vitamin A
# 180 units of vitamin B
# 140 units of vitamin C
# 180 units of vitamin D
# 350 units of vitamin E
# Task is to find the quantities of each different food in order 
#to obtain the specified amounts of the necessary vitamins.

# The equations -->
# x1 + 9x2 + 2x3 + x4 + x5 = 170
# 10x1 + x2 + 2x3 + x4 + x5 = 180
# x1 + 5x3 + x4 + x5 = 140
# 2x1 + x2 + x3 + 2x4 + 9x5 = 180
# 2x1 + x2 + 2x3 + 13x4 + 2x5 = 350

In [6]:
a = np.array([
    [1, 9, 2, 1, 1],
    [10, 1, 2, 1, 1],
    [1, 0, 5, 1, 1],
    [2, 1, 1, 2, 9],
    [2, 1, 2, 13, 2]
])

b = np.array([170, 180, 140, 180, 350]).reshape(5, 1)

np.linalg.solve(a, b)

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])

In [12]:
#Solving Problems Using Matrix Inverses
a = np.array([
    [1, 9, 2, 1, 1],
    [10, 1, 2, 1, 1],
    [1, 0, 5, 1, 1],
    [2, 1, 1, 2, 9],
    [2, 1, 2, 13, 2],
])

b = np.array([170, 180, 140, 180, 350]).reshape((5, 1))

#Check the determination

d = linalg.det(a)
d

45101.99999999999

In [13]:
#solve
a_inv = linalg.inv(a)
x = a_inv @ b
x

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])

In [15]:
#Solve polynomial
# a0 + a1 + a3 = 5
# a0 + 2.a1 + 4.a2 = 13
# a0 + 3a2 + 9a3 = 25

a = np.array([
    [1, 1, 1],
    [1, 2, 4],
    [1, 3, 9]
])

b = np.array([5, 13, 25]).reshape((3, 1))

d = linalg.det(a)
d

1.9999999999999996

In [16]:
ans = linalg.inv(a) @ b
ans

array([[1.],
       [2.],
       [2.]])