In [1]:
import numpy as np

In [2]:
#Make a 2D matrix
a = np.array([[1, 2],[3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
#Data type
a.dtype

dtype('int64')

In [5]:
#Dimension
a.shape

(3, 2)

In [6]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
#Create a vector using np.array
v = np.array([1,2,3])
v

array([1, 2, 3])

In [9]:
#shape of the vector
v.shape

(3,)

In [14]:
#make it 2D
v = v.reshape(1, 3)
v

array([[1, 2, 3]])

In [13]:
v.shape

(1, 3)

In [16]:
#Create a matrix with value of zeros
z = np.zeros((3, 2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
z.dtype

dtype('float64')

In [19]:
#create array with value one
o = np.ones((2, 3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#Create a matrix with random value
r = np.random.rand(3, 2)
r

array([[0.59123069, 0.03642548],
       [0.52798834, 0.97974198],
       [0.28847453, 0.81082507]])

In [22]:
#Obtain an array with random elements taken from a normal distribution with zero mean and unit variance
new = np.random.randn(3, 2)
new

array([[ 1.51717057, -1.32936528],
       [ 1.25767534,  1.16255112],
       [ 0.24704302, -0.64171249]])

In [25]:
#Create a matrix filled with elements equal to 10
ten = 10 * np.ones((3, 2))
ten

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [29]:
#Multiplication of array
b = np.array([[2, 2], [5, 5], [4, 5]])
ten * b

array([[20., 20.],
       [50., 50.],
       [40., 50.]])

In [32]:
#Matrix Multiplication
a = np.array([[2, 3, 1], [4, 5, 3]])
b = np.array([[1], [4], [5]])
print(a.shape)
print(b.shape)
a @ b

(2, 3)
(3, 1)


array([[19],
       [39]])

In [33]:
#Matrix multiplication with numpy
np.dot(a, b)

array([[19],
       [39]])